name: atacseq-accessibility
channels:
  - bioconda
  - conda-forge
dependencies:
  - trim-galore
  - bowtie2
  - samtools
  - picard
  - bedtools
  - deeptools
  - macs3
  - homer
  - subread
  - multiqc
