name: viral-phylodynamics
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mafft
  - trimal
  - iqtree
  - treetime
  - augur
  - samtools
  - bcftools
  - python=3.10
  - pandas
  - matplotlib
  - biopython
  - importlib_resources
