name: cnv-detection-wes
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastp
  - bwa-mem2
  - samtools
  - picard
  - mosdepth
  - cnvkit
  - control-freec
  - gatk4
  - bcftools
  - bedtools
  - python>=3.9
  - pandas
  - numpy
  - scipy
