name: edna-metabarcoding
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cutadapt
  - vsearch
  - swarm
  - blast
  - fastqc
  - samtools
  - seqkit
  - multiqc
  - pandas
  - scipy
  - r-vegan
